Init commit
skushnerchuk/golang pull request #6
Opened 2024-01-21 10:12 UTC by skushnerchuk

## Домашнее задание №6 «Пайплайн»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - pipeline.go ~55 строк

### Критерии оценки
- [ ] CI-пайплайн зелёный - 5 баллов
- [ ] Добавлены новые юнит-тесты - до 2 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2024-01-21 10:53 UTC, vladislavmass requested changes
Хорошее начало, но в коде есть потенциальный лок. Рекомендую рассмотреть обе ситуации приведенные в комментарии. А также не вижу новых тестов, без них не смогу поставить больше 8 балов

2024-01-21 10:53 UTC, vladislavmass commented on hw06_pipeline_execution/pipeline.go
> +				output <- v
Тут может произойти лок, если из канала уже некому читать или читающий сам висит на записи в канал из которого никто не читает

2024-01-31 07:50 UTC, skushnerchuk commented on hw06_pipeline_execution/pipeline.go
> +				output <- v
Немного поправил и добавил тесты
Я не совсем понимаю, где тут может быть лок.
Каждый стейдж выполняется в своей горутине, и выполняются они последовательно, а не параллельно
Прошу подсказки :)

2024-02-01 17:09 UTC, vladislavmass commented on hw06_pipeline_execution/pipeline.go
> +				output <- v
Почему  они выполняются последовательно? они выполняются паралельно. Просто пока текущий пайп обрабатывает текущий элемент, то предыдущий пайп обрабатывает значение, которое для текущего пайпа станет следующим.

2024-02-01 17:11 UTC, skushnerchuk commented on hw06_pipeline_execution/pipeline.go
> +				output <- v
Да, согласен, ступил )

2024-02-01 17:16 UTC, vladislavmass commented on hw06_pipeline_execution/pipeline.go
> +				output <- v
У нас наш стейдж зажат между двумя функциями которые запускаются в методе  stageRunner. И вот предположим такую ситуацию. stageRunner который дает данные на вход нашему стейджу получает данные и проваливается в case где происходит пересылка. Там он ждет пока из него не прочитают. В это время прилетает done и stageRunner который получает данные из нашего стеджа выходит по done. После этого наш стейдж окончивает работу и пытается отправить данные в канал. Но из канала уже никто не читает поэтому стейдж завис. А вместе с тем завис и stageRunner который пытается отправить данные в наш stage.

2024-02-04 14:18 UTC, skushnerchuk commented on hw06_pipeline_execution/pipeline.go
> +				output <- v
Идей, кроме как сделать чтение не блокирующим, нет.
Если это неверное решение - прошу подсказки снова )

2024-02-04 14:49 UTC, vladislavmass commented on hw06_pipeline_execution/pipeline.go
> +				output <- v
Это не сработает. Так как у вас лок не на чтение, а на запись. Подумайте о том, что бы добавить реакцию на done не только при чтение но и при записе. А также о том, что бы перед закрытием канал вычитать из него информацию, но при этом ничего с ней не делать.

2024-02-12 13:04 UTC, vladislavmass approved these changes

2024-02-12 13:06 UTC, merged