init commit
skushnerchuk/golang pull request #9
Opened 2024-03-28 13:15 UTC by skushnerchuk

## Домашнее задание №9 «Валидатор структур»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)

### Критерии оценки
- [ ] Пайплайн зелёный - 3 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2024-03-28 20:00 UTC, vladislavmass requested changes

2024-03-28 20:00 UTC, hungry-honeybadger commented on hw09_struct_validator/validator_slice.go
> +			errors = append(errors, ValidationError{Field: name, Err: ErrValidationType})
Это не ошибка валидации, это программная ошибка и мы не должны добавлять ее в слайс, а должны просто вернуть эту ошибку. Так как ошибка валидации это ошибка на которую должен отреагировать пользователь, а вот то, что на поле навесили не подхоядщий валидатор это уже ошибка программиста

2024-03-28 20:00 UTC, hungry-honeybadger commented on hw09_struct_validator/validator_int.go
> +			errors = append(errors, ValidationError{Field: name, Err: ErrValidationUnsupportedRule})
Это не ошибка валидации, это программная ошибка и мы не должны добавлять ее в слайс, а должны просто вернуть эту ошибку. Так как ошибка валидации это ошибка на которую должен отреагировать пользователь, а вот то, что на поле навесили не подхоядщий валидатор это уже ошибка программиста

2024-03-28 20:00 UTC, vladislavmass commented on hw09_struct_validator/validator_slice.go
> +			errors = append(errors, validateString(v, name, rules)...)
А то будет хорошей идеей в массиве строк из 1 млн элементов 1 млн раз например компилировать регулярные выражения? Или парсить строку в число?

2024-03-29 07:18 UTC, skushnerchuk commented on hw09_struct_validator/validator_slice.go
> +			errors = append(errors, validateString(v, name, rules)...)
По условию задачи валидируется ведь каждый элемент слайса

2024-03-29 07:35 UTC, vladislavmass commented on hw09_struct_validator/validator_slice.go
> +			errors = append(errors, validateString(v, name, rules)...)
Да, валидируется каждый элемент. Но валидатор можно создать 1 раз и применить его к каждому элементу слайса. Именно такой подход будет наиболее оптимальным

2024-04-01 19:41 UTC, vladislavmass approved these changes

2024-04-02 06:07 UTC, merged